name             'mapr-cluster'
maintainer       'Eric Moritz'
maintainer_email 'ericmoritz@gmail.com'
license          'All rights reserved'
description      'Installs/Configures mapr-cluster'
long_description 'Installs/Configures mapr-cluster'
version          '0.0.0'

depends 'ntp'
depends 'consul'
depends 'consul-template'
