name             'mapr_consul'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mapr_consul'
long_description 'Installs/Configures mapr_consul'
version          '0.1.0'

depends 'ntp'
depends 'consul'
